site_name: Example Unity Package
site_author: Trouble Cat Studios
site_description: >-
  An example of how to structure a Unity Package Project

# Repository
repo_name: troublecatstudios/unity-package-example
repo_url: https://github.com/troublecatstudios/unity-package-example

site_url: 'https://troublecat.io/unity-package-example/'

# Copyright
copyright: Copyright &copy; 2024 - 2025 Trouble Cat Studios

extra:
  version:
    provider: mike

theme:
  name: material
  custom_dir: docs/overrides
  palette:
    scheme: troublecat
  features:
    - search.highlight
    - search.suggest
    - navigation.top
    - navigation.sections
    - navigation.tabs
    - content.code.annotate
    - content.code.copy
    - toc.follow
  font:
    text: Noto Sans
    code: Anonymous Pro
  logo: images/troublecat-logo-trans-wht.png
  favicon: images/favicon.ico
plugins:
  - search
  - include_dir_to_nav
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      pygments_lang_class: true
  - pymdownx.superfences:
      custom_fences:
        # Mermaid diagrams
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.escapeall:
      hardbreak: true
extra_javascript:
  - https://unpkg.com/mermaid@10.6.1/dist/mermaid.min.js
extra_css:
  - stylesheets/troublecat.css
nav:
  - Home: README.md
  - Features:
    - features/continuous-integration.md
    - features/deployment.md
    - features/documentation-site.md
    - features/openupm.md
  - How to:
    - howto/create-a-release.md
  - Reference:
      - reference/README.md
      - UnityPackageExample: reference/UnityPackageExample
      - UnityPackageExampleEditor: reference/UnityPackageExampleEditor
