name: Check Pull Request

on:
  pull_request:
    branches:
    - stable
    types:
    - assigned
    - unassigned
    - labeled
    - unlabeled
    - opened
    - edited
    - closed
    - reopened
    - synchronize
    - ready_for_review

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # Retrieve the current PR number and body
      # -----------------------------
      - uses: 8BitJonny/gh-get-current-pr@3.0.0
        id: PR
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Verbose setting SHA when using Pull_Request event trigger to fix #16
          sha: ${{ github.event.pull_request.head.sha }}
          # Only return if PR is still open
          filterOutClosed: true
          # Only return if PR is not in draft state
          filterOutDraft: false

      # Find any previous bot comments so we can update them
      # -----------------------------
      - name: Find Comment
        uses: peter-evans/find-comment@v3
        id: FindComment
        with:
          issue-number: ${{ steps.PR.outputs.number }}
          body-includes: Pull Request Lint Results

      # Validate PR
      # -----------------------------
      - uses: actions/checkout@v4
      - name: Validate Pull Request
        id: Validation
        if: success() && steps.PR.outputs.number
        uses: actions/github-script@v6
        with:
          script: |
            const pr = ${{ steps.PR.outputs.pr }};
            const script = require('./.github/scripts/check-pr.js');
            await script({github, context, core, pr});

      # Post status back
      # -----------------------------
      - name: Post Comment (Passed)
        if: success()
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.FindComment.outputs.comment-id }}
          issue-number: ${{ steps.PR.outputs.number }}
          body: |
            ## Pull Request Lint Results
            :tada: This PR has been automatically checked and passes our linting, congrats! If any warnings were noticed they'll be included below.
            ${{ steps.Validation.outputs.warnings }}
            ${{ steps.Validation.outputs.remarks }}
          edit-mode: replace
          reactions: hooray

      - name: Post Comment (Failed)
        if: failure()
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.FindComment.outputs.comment-id }}
          issue-number: ${{ steps.PR.outputs.number }}
          body: |
            ## Pull Request Lint Results
            :grimacing: Oops, looks like this PR needs some changes before merging.
            ${{ steps.Validation.outputs.reasons }}
            ${{ steps.Validation.outputs.warnings }}
            ${{ steps.Validation.outputs.remarks }}
          edit-mode: replace

