name: Deploy Documentation Site (develop)

on:
  workflow_dispatch:
  push:
    branches:
      - develop

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0

      - uses: ./.github/actions/docs
        id: docs
        with:
          version: develop
