name: Release Automation

on:
  workflow_dispatch:
    inputs:
      source_tag:
        type: string
        description: Source Tag
  push:
    tags:
    - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    # Create/Update the upm tag
    # -----------------------------
    - uses: ./.github/actions/upm
      id: upm
      with:
        source_tag: ${{ inputs.source_tag || github.ref_name }}
